# not
print ("not False             |" ,)
print ( not False)
print ("not True              |" ,)
print (not True)
print ("------------------------------")

# OR
print ("True  or False        |" ,)
print (True or False)
print ("True or True          |" ,)
print (True or True )
print ("False  or True        |" ,)
print (False or True)
print ("False or False        |" ,)
print (False or False)
print ("------------------------------")

# AND
print ("True  and False       |" ,)
print (True and False)
print ("True  and True        |" ,)
print (True and True )
print ("False and True        |" ,)
print (False and True)
print ("False and False       |" ,)
print (False and False)
print ("------------------------------")

# NOT OR
print ("not (True  or  False) |" ,)
print (not (True or  False) )
print ("not (True  or  True ) |" ,)
print (not (True or  True ))
print ("not (False or  True ) |" ,)
print (not (False or  True))
print ("not (False or  False) |" ,)
print (not (False or  False))
print ("------------------------------")

# NOT AND
print ("not (True  and False) |" ,)
print (not (True and False) )
print ("not (True  and True ) |" ,)
print (not (True and True ))
print ("not (False and True ) |" ,)
print (not (False and True))
print ("not (False and False) |" ,)
print (not (False and False))
print ("------------------------------")

# !=
print ("1 != 0                |" ,)
print (1 != 0)
print ("1 != 1                |" ,)
print (1 != 1)
print ("0 != 1                |" ,)
print (0 != 1)
print ("0 != 0                |" ,)
print (0 != 0)
print ("------------------------------")

# ==
print ("1 == 0                |" ,)
print (1 == 0)
print ("1 == 1                |" ,)
print (1 == 1)
print ("0 == 1                |" ,)
print (0 == 1)
print ("0 == 0                |" ,)
print (0 == 0)
print ("------------------------------")
